#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_logout:
    path: /logout
    methods: GET

contact:
    path: /{_locale}/contact
    controller: App\Controller\DefaultController::contact
    requirements:
        _locale: en|fr|de
